enum ActionEnums {
  CAN_LOGIN = 'CAN_LOGIN',
  VIEW_HOMEPAGE = 'VIEW_HOMEPAGE',
  VIEW_CALENDAR = 'VIEW_CALENDAR',
  VIEW_MANAGER = 'VIEW_MANAGER',
  UPDATE_MANAGER = 'UPDATE_MANAGER',
}

export default ActionEnums;
